### ISSUE TITLE
home assist and nodered

### ISSUE THREAD

**Issue by Mateiuc** [blechdom/node-red-contrib-dmxusbpro#4]
hi i got this error when i try to install in hassio

2023-01-30T00:36:23.617Z Install : node-red-contrib-dmxusbpro 1.0.4

2023-01-30T00:36:24.843Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-dmxusbpro@1.0.4
2023-01-30T00:36:26.560Z [err] npm
2023-01-30T00:36:26.562Z [err]  WARN config
2023-01-30T00:36:26.562Z [err]  production Use `--omit=dev` instead.
2023-01-30T00:36:38.605Z [err] npm
2023-01-30T00:36:38.605Z [err]  ERR! code 1
2023-01-30T00:36:38.606Z [err] npm ERR! 
2023-01-30T00:36:38.606Z [err] path /config/node-red/node_modules/serialport
2023-01-30T00:36:38.612Z [err] npm ERR!
2023-01-30T00:36:38.612Z [err]  command failed
2023-01-30T00:36:38.612Z [err] npm ERR! command sh -c prebuild-install || node-gyp rebuild
2023-01-30T00:36:38.612Z [err] npm ERR!
2023-01-30T00:36:38.613Z [err]  gyp info it worked if it ends with ok
2023-01-30T00:36:38.613Z [err] npm ERR! gyp info using node-gyp@9.3.0
2023-01-30T00:36:38.613Z [err] npm ERR! gyp info using node@18.12.1 | linux | arm64
2023-01-30T00:36:38.613Z [err] npm ERR! gyp ERR! find Python 
2023-01-30T00:36:38.613Z [err] npm ERR!
2023-01-30T00:36:38.614Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2023-01-30T00:36:38.614Z [err] npm ERR!
2023-01-30T00:36:38.615Z [err]  gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python 
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2023-01-30T00:36:38.615Z [err] npm
2023-01-30T00:36:38.615Z [err]  ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2023-01-30T00:36:38.615Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2023-01-30T00:36:38.615Z [err] npm
2023-01-30T00:36:38.618Z [err]  ERR! gyp ERR! find Python - Set the npm configuration variable python:
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! find Python 
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! configure error 
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at exithandler (node:child_process:420:5)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! System Linux 5.15.84-v8
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/serialport
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! node -v v18.12.1
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.0
2023-01-30T00:36:38.618Z [err] npm ERR! gyp ERR! not ok
2023-01-30T00:36:38.624Z [err] 
2023-01-30T00:36:38.625Z [err] npm ERR! A complete log of this run can be found in:
2023-01-30T00:36:38.625Z [err] npm
2023-01-30T00:36:38.625Z [err]  ERR!     /root/.npm/_logs/2023-01-30T00_36_26_440Z-debug-0.log
2023-01-30T00:36:38.664Z rc=1

**Comment by mihaichrapan** [comment]
How did you solve it? And it gives me the same error.
It's just that I'm also a very beginner in node red.

Thanks

**Comment by Mateiuc** [comment]
> How did you solve it? And it gives me the same error. It's just that I'm also a very beginner in node red.
> 
> Thanks

sorry sir... I give up, I renounced to home assistant, to many problems for me with node red.
